### ISSUE TITLE
Implemented some new features

### ISSUE THREAD

**Issue by dreampowder** [adar2378/draggable_widget#1]
Hello, first of all thanks for this library. 

I've implemented some new features in my own fork, and couldn't make a successful pull request to your repo, so please feel free to implement these features to your own library too. 

1- Implemented "center" position: it is not a snapping location but still usefull in some cases. 

2- Implemented a touch delay feature: It is required when we have a button at the edge of the draggable widget (i.e a video player), because when we click on the button, onPointerUp event triggers and widget moves to the relevant corner in some cases. 

you can check from https://github.com/dreampowder/draggable_widget

draggable_widget.dat / anchor_docket.dart

thanks again!.

**Comment by adar2378** [comment]
Hi, thanks for your contribution. Could you create a pull request?

**Comment by dreampowder** [comment]
sure, but i accidentally added example/ios files in to the project
